source 'https://supermarket.chef.io'

metadata

cookbook 'jenkins', '~> 2.3.1'
cookbook 'apache2', '~> 3.1.0'
cookbook 'chef-vault', '~> 1.3.0'
cookbook 'didata-base', '~> 1.0.0', git: 'git@github.com:DimensionDataDevOps/cookbook-didata-base.git', branch: 'master'
